function BuildVersionNumber($version_major, $version_minor, $buildNumber, $isTFSBuild) {
  if ($isTFSBuild -eq $false -or -not $buildNumber.Contains("_")) {
    $version = "$version_major.$version_minor.$buildNumber.0"
    Write-Host "Not a TFS build, setting version to $version"
    return $version
  }

  Write-Host "TFS build, calculating a build number from build date"

    $splitName = $buildNumber.split("_")
    $definitionName = $splitName[0]
    $splitDateAndRev = $splitName[1].split(".")

    # calculate build number
    $dateStr = $splitDateAndRev[0]
    $elapsedDays = ([datetime]::parseexact($dateStr, "yyyyMMdd",$null)) - (Get-Date "2012-11-20")
    $numericBuildNumber = $elapsedDays.TotalDays

    #calculate revision number
    $rawRev = [int32]::Parse($splitDateAndRev[1])
    $revOffset = 0
    $splitDateAndRev = $splitName[2].split(".")
    $rev = $rawRev + $revOffset

    $version = "$version_major.$version_minor.$numericBuildNumber.$rev"

  Write-Host "setting version to $version"
  return $version
}

function create_commonAssemblyInfo($version, $applicationName, $date, $number, $filename, $currentYear) {
"using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyTitle(""Well Data Viewer"")]
[assembly: AssemblyDescription(""Well Data Viewer"")]
[assembly: AssemblyVersionAttribute(""$version"")]
[assembly: AssemblyFileVersionAttribute(""$version"")]
[assembly: AssemblyCopyrightAttribute(""Copyright (c) 2008 - $currentYear"")]
[assembly: AssemblyCompany(""Qv21 Technologies"")]"	| out-file $filename -encoding "ASCII" -Force
}

function create_WellDataAssemblyInfo($version, $applicationName, $date, $number, $filename, $currentYear) {
"using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyTitle(""Well Data Viewer"")]
[assembly: AssemblyDescription(""Well Data Viewer"")]
[assembly: AssemblyVersionAttribute(""$version"")]
[assembly: AssemblyFileVersionAttribute(""$version"")]
[assembly: AssemblyCopyrightAttribute(""Copyright (c) 1998 - $currentYear"")]
[assembly: AssemblyCompany(""Qv21 Technologies"")]
[assembly: AssemblyMetadata(""SquirrelAwareVersion"", ""1"")]"	| out-file $filename -encoding "ASCII" -Force
}

export-modulemember -function BuildVersionNumber
export-modulemember -function create_commonAssemblyInfo
export-modulemember -function create_WellDataAssemblyInfo
